/* GENERATED by scripts/build-prototype.py — do not edit. */
/* Standalone frontend prototype: mock backend bundled in, no server/DB. */
/* Debug traces (trace/console.log) are kept below but COMMENTED OUT. */
(function () {
'use strict';
/* ── js/debug.js ── */
// Debug tracer — a learning/debugging aid for following the app end-to-end.
//
// OFF by default (zero console noise in normal use). Turn it ON by opening the
// app with ?debug=1 in the URL — e.g.  http://127.0.0.1:5500/?debug=1
// (or set window.NRN_DEBUG = true before the modules load).
//
// trace(...) is just console.log under the hood — output shows in DevTools →
// Console. To find/remove every trace later: grep the codebase for `trace(`.
const DEBUG =
  new URLSearchParams(window.location.search).has('debug') || window.NRN_DEBUG === true;

function trace(...args) {
  if (DEBUG) console.log('%c[trace]', 'color:#2563EB;font-weight:700', ...args);
}

/* ── js/icons.js ── */
// Lucide icons — vendored (copied) as inline SVG strings.
//
// SOURCE / ATTRIBUTION: Lucide, https://lucide.dev — open source, ISC License.
// Every path string below is copied VERBATIM from Lucide. To see or re-copy any of
// them, open the icon's page and use its "Copy SVG" button:
//     https://lucide.dev/icons/<name>          e.g. https://lucide.dev/icons/dna
// Raw source files (same data): https://unpkg.com/lucide-static/icons/<name>.svg
//     and https://github.com/lucide-icons/lucide/tree/main/icons
//
// WHY inline instead of `import { createIcons } from 'lucide'` or the CDN <script>:
// those need npm/a bundler or an internet connection. This project is deliberately
// no-npm and must work OFFLINE and over file:// (school Chromebooks + the double-
// click prototype), so we paste the SVGs. They also inherit the text colour via
// `currentColor`, so icons re-theme with the palette automatically.
//
// Each ICONS[name] is just the inner elements of that Lucide SVG; icon(name) wraps
// them in a consistent <svg>. To add one: copy its inner <path>/<circle>/… here.

const ICONS = {
  dna: '<path d="m10 16 1.5 1.5"/><path d="m14 8-1.5-1.5"/><path d="M15 2c-1.798 1.998-2.518 3.995-2.807 5.993"/><path d="m16.5 10.5 1 1"/><path d="m17 6-2.891-2.891"/><path d="M2 15c6.667-6 13.333 0 20-6"/><path d="m20 9 .891.891"/><path d="M3.109 14.109 4 15"/><path d="m6.5 12.5 1 1"/><path d="m7 18 2.891 2.891"/><path d="M9 22c1.798-1.998 2.518-3.995 2.807-5.993"/>',
  'flask-conical': '<path d="M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2"/><path d="M6.453 15h11.094"/><path d="M8.5 2h7"/>',
  atom: '<circle cx="12" cy="12" r="1"/><path d="M20.2 20.2c2.04-2.03.02-7.36-4.5-11.9-4.54-4.52-9.87-6.54-11.9-4.5-2.04 2.03-.02 7.36 4.5 11.9 4.54 4.52 9.87 6.54 11.9 4.5Z"/><path d="M15.7 15.7c4.52-4.54 6.54-9.87 4.5-11.9-2.03-2.04-7.36-.02-11.9 4.5-4.52 4.54-6.54 9.87-4.5 11.9 2.03 2.04 7.36.02 11.9-4.5Z"/>',
  calculator: '<rect width="16" height="20" x="4" y="2" rx="2"/><line x1="8" x2="16" y1="6" y2="6"/><line x1="16" x2="16" y1="14" y2="18"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>',
  'book-open': '<path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/>',
  'notebook-pen': '<path d="M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4"/><path d="M2 6h4"/><path d="M2 10h4"/><path d="M2 14h4"/><path d="M2 18h4"/><path d="M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z"/>',
  book: '<path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20"/>',
  landmark: '<path d="M10 18v-7"/><path d="M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z"/><path d="M14 18v-7"/><path d="M18 18v-7"/><path d="M3 22h18"/><path d="M6 18v-7"/>',
  globe: '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
  'trending-up': '<path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/>',
  hand: '<path d="M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2"/><path d="M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2"/><path d="M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8"/><path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15"/>',
  sprout: '<path d="M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3"/><path d="M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4"/><path d="M5 21h14"/>',
  'graduation-cap': '<path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
  brain: '<path d="M12 18V5"/><path d="M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4"/><path d="M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5"/><path d="M17.997 5.125a4 4 0 0 1 2.526 5.77"/><path d="M18 18a4 4 0 0 0 2-7.464"/><path d="M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517"/><path d="M6 18a4 4 0 0 1-2-7.464"/><path d="M6.003 5.125a4 4 0 0 0-2.526 5.77"/>',
  settings: '<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/>',
  'user-round': '<circle cx="12" cy="8" r="5"/><path d="M20 21a8 8 0 0 0-16 0"/>',
  plus: '<path d="M5 12h14"/><path d="M12 5v14"/>',
  x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
  'log-out': '<path d="m16 17 5-5-5-5"/><path d="M21 12H9"/><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>',
  'layout-dashboard': '<rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/>',
  'circle-check-big': '<path d="M21.801 10A10 10 0 1 1 17 3.335"/><path d="m9 11 3 3L22 4"/>',
};

// Map a subject name to a sensible Lucide icon (falls back to a book).
const SUBJECT_ICON = {
  english: 'notebook-pen',
  mathematics: 'calculator',
  math: 'calculator',
  maths: 'calculator',
  biology: 'dna',
  chemistry: 'flask-conical',
  physics: 'atom',
  history: 'landmark',
  geography: 'globe',
  economics: 'trending-up',
};

function subjectIcon(name) {
  return SUBJECT_ICON[(name || '').trim().toLowerCase()] || 'book';
}

// Return a complete inline <svg> string for `name`, sized and theme-aware.
function icon(name, { size = 20, cls = '' } = {}) {
  const inner = ICONS[name] || ICONS.book;
  return (
    `<svg class="icon ${cls}" width="${size}" height="${size}" viewBox="0 0 24 24" ` +
    'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" ' +
    `stroke-linejoin="round" aria-hidden="true">${inner}</svg>`
  );
}

// Fill every element that has a data-icon="<name>" attribute with its SVG.
// Lets static HTML declare icons (e.g. <div class="ob-icon" data-icon="hand">).
function hydrateIcons(root = document) {
  root.querySelectorAll('[data-icon]').forEach((el) => {
    const size = Number(el.dataset.iconSize) || 24;
    el.innerHTML = icon(el.dataset.icon, { size });
  });
}

/* ── js/schedule.js ── */
// Scheduling helpers — the spaced-repetition maths, on the client.
//
// Pure functions over plain topic data ({ reviewCount, nextDue }). Kept UI-free
// and backend-agnostic so the same logic drives the mock now and the real Flask
// engine later. Intervals are Carpenter (2012): 1 · 3 · 7 · 14 days (max 14).
//
// NOTE: the mock uses the browser's date for "today"; the real backend is the
// single source of truth (server date.today()) — see CLAUDE.md.


const INTERVALS = { 1: 1, 2: 3, 3: 7 };
const INTERVAL_MAX = 14;

function intervalFor(reviewCount) {
  return INTERVALS[reviewCount] || INTERVAL_MAX;
}

// Format a Date as a LOCAL ISO day (YYYY-MM-DD). Deliberately NOT toISOString()
// — that returns UTC, which shifts the date by a day in NZ (UTC+12/13) and would
// make "due tomorrow" read as "due today". (The real backend uses server date.)
function fmtLocal(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function todayISO() {
  return fmtLocal(new Date());
}

function addDaysISO(iso, days) {
  const d = new Date(iso + 'T00:00:00'); // parse as local midnight
  d.setDate(d.getDate() + days);
  return fmtLocal(d);
}

// Whole days from a → b (b - a). Positive = b is later.
function daysBetween(aISO, bISO) {
  return Math.round((new Date(bISO + 'T00:00:00') - new Date(aISO + 'T00:00:00')) / 86400000);
}

// Classify a topic for display + priority ordering.
//   new     — never reviewed (nextDue null) → intro queue
//   overdue — nextDue is in the past
//   due     — nextDue is today
//   ok      — nextDue is in the future
function statusOf(topic, today = todayISO()) {
  if (!topic.nextDue) return { status: 'new', days: 0 };
  const diff = daysBetween(topic.nextDue, today); // today - nextDue
  if (diff > 0) return { status: 'overdue', days: diff };
  if (diff === 0) return { status: 'due', days: 0 };
  return { status: 'ok', days: -diff }; // due in |diff| days
}

// Status → a short display badge { cls, label }, e.g. "2d overdue" / "NEW".
function statusBadge(topic) {
  const st = statusOf(topic);
  if (st.status === 'new') return { cls: 'is-new', label: 'NEW' };
  if (st.status === 'overdue') return { cls: 'is-overdue', label: `${st.days}d overdue` };
  if (st.status === 'due') return { cls: 'is-due', label: 'due today' };
  return { cls: 'is-ok', label: `due in ${st.days}d` };
}

// Coverage = topics reviewed at least once ÷ total, as a percentage.
function coverageOf(topics = []) {
  if (!topics.length) return 0;
  const reviewed = topics.filter((t) => (t.reviewCount || 0) >= 1).length;
  return Math.round((reviewed / topics.length) * 100);
}

// Build today's priority feed from all subjects: most-overdue first, then NEW,
// capped at `cap`. Returns the capped list + counts for the encouraging framing.
function buildPriorities(subjects = [], cap = 5) {
  const today = todayISO();
  const items = [];
  subjects.forEach((s) =>
    (s.topics || []).forEach((t) => {
      const st = statusOf(t, today);
      items.push({ ...t, subjectName: s.name, status: st.status, days: st.days });
    }),
  );
  const active = items
    .filter((i) => i.status === 'overdue' || i.status === 'due')
    .sort((a, b) => b.days - a.days); // most overdue first
  const news = items.filter((i) => i.status === 'new');
  const ordered = [...active, ...news];
  // trace('schedule: buildPriorities', {  // debug trace (disabled in prototype)
    total: items.length,
    overdue: items.filter((i) => i.status === 'overdue').length,
    shown: Math.min(ordered.length, cap),
  });
  return {
    shown: ordered.slice(0, cap),
    moreCount: Math.max(0, ordered.length - cap),
    overdue: items.filter((i) => i.status === 'overdue').length,
    dueToday: items.filter((i) => i.status === 'due').length,
  };
}

/* ── js/config.js ── */
// ✅
// Configuration & constants.
//
// Split-origin setup: the API runs on a different origin to this static SPA,
// so calls use an absolute base URL. Override at runtime by setting
// `window.NRN_API_BASE` before the module scripts load (e.g. for deployment).
//
// Host port 5050 (not 5000): macOS AirPlay Receiver occupies 5000, so the API's
// published host port is 5050 (see docker-compose.yml). Keep this in sync with it.

//established 
const API_BASE = window.NRN_API_BASE || 'http://127.0.0.1:5050'; //door number that the flask is running. || = or, can define  window.NRN_API_BASE for the actual web

// Backend selection. The SPA defaults to an in-browser MOCK backend so it runs
// standalone for prototype/mockup review — only HTML/CSS/JS, no Flask, no DB.
// It switches to the real API when a real base URL is configured (deploy injects
// window.NRN_API_BASE) or you pass ?real=1. The mock mirrors the real API
// contract, so nothing else changes. See js/api.mock.js + docs/dev-and-test.md.
//   (default)  → mock        ?real=1 → real API        ?mock=1 → force mock
const _params = new URLSearchParams(window.location.search)//look at messy text start at ? mark; URLSearchParams= built in tool to turn messy string to easy to use checklist
const USE_MOCK = _params.has('mock')
  ? /* is teh condition to the left true*/ true // Rule 1: Is '?mock' in the URL? If yes, USE_MOCK = true.No then move below // ? or : used for assign a single value immediately 
  :  /* otherwise*/_params.has('real') // Rule 2: If not, is '?real' in the URL? If yes, USE_MOCK = false!
    ? false
    : typeof window.NRN_USE_MOCK === 'boolean' // Otherwise, did the developer explicitly set a true/false setting in the window settings (NRN_USE_MOCK)?
      ? window.NRN_USE_MOCK
      : !window.NRN_API_BASE; // no real API configured → mock

const TOKEN_KEY = 'ncea_token'; //label written on the storage locker-> use label key to open the box

const DEFAULT_TOPIC_EMOJI = '📚';

/* ── js/dom.js ── */
// DOM helpers — selectors, show/hide, HTML escaping, toast, and modal plumbing.

const $ = (sel, root = document) => root.querySelector(sel); //sel (selector= what you're hunting for), searches the root = document ; $= grab 1 specific item
const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));//$$ grab every matching item on the screen; array  from packs the messy node list (of all the items) into clean js array(list)

function show(el) {
  if (el) el.classList.remove('hidden');
}
function hide(el) {
  if (el) el.classList.add('hidden');
}

// Escape user-supplied text before inserting into innerHTML (XSS-safe).
function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

let toastTimer = null;
function toast(msg) {
  const el = $('#toast');
  if (!el) return;
  el.textContent = msg;
  void el.offsetWidth; // force reflow so the transition re-fires
  el.classList.add('show');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => el.classList.remove('show'), 2200);
}

function openModalFromHTML(html) {
  const ov = $('#modal-overlay');
  ov.innerHTML = html;
  ov.classList.add('show');
  ov.onclick = (e) => {
    if (e.target === ov) closeModal();
  };
  return ov;
}

function closeModal() {
  const ov = $('#modal-overlay');
  ov.classList.remove('show');
  ov.onclick = null;
  setTimeout(() => {
    if (!ov.classList.contains('show')) ov.innerHTML = '';
  }, 220);
}

// Run an async action while disabling a button and showing pending text, so
// API calls never feel frozen. Restores the original label afterwards.
async function withPending(btn, pendingText, fn) {
  if (!btn) return fn();
  const original = btn.textContent;
  btn.disabled = true;
  btn.textContent = pendingText;
  try {
    return await fn();
  } finally {
    btn.disabled = false;
    btn.textContent = original;
  }
}

/* ── js/state.js ── */
// Central app state. A single mutable object so modules share one source of
// truth (ES module exports are live bindings — mutate properties, don't reassign).

const state = { //run only once the site first loads up
  currentUser: null, // { id, name, email, yearLevel, onboarding_done }
  authMode: 'login', // 'login' | 'signup'
  onboarding: {
    step: 1, // 1 | 2 | 3 (which card/step user is on)
    createdSubject: null, // { id, name, emoji, colour }
    addedTopics: [], // string[]
  },
};

function resetOnboarding() {
  state.onboarding.step = 1;
  state.onboarding.createdSubject = null;
  state.onboarding.addedTopics = [];
}

/* ── js/api.mock.js ── */
// In-browser mock backend — front-end-only dev (no Flask, no SQLite).
//
// Enabled by `?mock=1` (see config.js USE_MOCK). It mirrors the real API
// contract exactly — same request bodies, same response shapes, same status
// codes and friendly error messages — so the SPA can't tell the difference and
// switching to the real backend is just removing the flag.
//
// Data persists in localStorage (key `nrn_mock_db`) so reloads keep your state.
// Tokens are `mock.<userId>` (no real crypto — this is a dev stand-in only).


const DB_KEY = 'nrn_mock_db';
const MIN_PASSWORD_LEN = 4;
const MAX_NAME_LEN = 80;
const LATENCY_MS = 120; // a little delay so pending/disabled UI states are visible

function load() {
  let db;
  try {
    db = JSON.parse(localStorage.getItem(DB_KEY)) ?? blank();
  } catch {
    db = blank();
  }
  db.reviews = db.reviews || []; // added in v3 — keep older saved DBs working
  return db;
}
function blank() {
  return { users: [], subjects: [], topics: [], reviews: [], seq: 0 };
}
function save(db) {
  localStorage.setItem(DB_KEY, JSON.stringify(db));
}
function nextId(db) {
  db.seq += 1;
  return db.seq;
}

// Mirror of errors.py: throws an Error carrying .status, like the real api().
function fail(message, status = 400) {
  const err = new Error(message);
  err.status = status;
  throw err;
}
function requireStr(value, field, maxLen = MAX_NAME_LEN) {
  const text = typeof value === 'string' ? value.trim() : '';
  if (!text) fail(`Please enter a ${field}.`);
  if (text.length > maxLen) fail(`That ${field} is too long (max ${maxLen} characters).`);
  return text;
}
function userFromToken(db, token) {
  const id = token && token.startsWith('mock.') ? Number(token.slice(5)) : NaN;
  const user = db.users.find((u) => u.id === id);
  if (!user) fail('Authentication required.', 401);
  return user;
}

// Serialisers — match the Flask route shapes.
const userPublic = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  yearLevel: u.yearLevel,
  onboarding_done: u.onboarding_done,
});
const subjectPublic = (s) => ({ id: s.id, name: s.name, emoji: s.emoji, colour: s.colour });
const topicPublic = (t) => ({
  id: t.id,
  subjectId: t.subjectId,
  name: t.name,
  emoji: t.emoji,
  standardNumber: t.standardNumber,
  reviewCount: t.reviewCount,
  nextDue: t.nextDue,
});

// Route table keyed by "METHOD path". Each handler gets (db, body, token).
const routes = {
  'POST /api/auth/signup': (db, body) => {
    const name = requireStr(body.name, 'name');
    const email = requireStr(body.email, 'email');
    const password = body.password || '';
    if (password.length < MIN_PASSWORD_LEN)
      fail(`Password must be at least ${MIN_PASSWORD_LEN} characters.`);
    if (db.users.some((u) => u.email.toLowerCase() === email.toLowerCase()))
      fail('An account with that email already exists.');
    const yearLevel = Number(body.yearLevel) || 12;
    const user = { id: nextId(db), name, email, password, yearLevel, onboarding_done: 0 };
    db.users.push(user);
    save(db);
    return { token: `mock.${user.id}`, user: userPublic(user) };
  },

  'POST /api/auth/login': (db, body) => {
    const email = (body.email || '').trim();
    const password = body.password || '';
    if (!email || !password) fail('Please enter your email and password.');
    const user = db.users.find((u) => u.email.toLowerCase() === email.toLowerCase());
    if (!user || user.password !== password) fail('Incorrect email or password.', 401);
    return { token: `mock.${user.id}`, user: userPublic(user) };
  },

  'GET /api/auth/me': (db, _body, token) => ({ user: userPublic(userFromToken(db, token)) }),

  'POST /api/auth/logout': () => ({ ok: true }),

  'PUT /api/user/onboarding': (db, _body, token) => {
    const user = userFromToken(db, token);
    user.onboarding_done = 1;
    save(db);
    return { ok: true };
  },

  'POST /api/subjects': (db, body, token) => {
    const user = userFromToken(db, token);
    const name = requireStr(body.name, 'subject name');
    if (db.subjects.some((s) => s.userId === user.id && s.name === name && !s.archived))
      fail(`You already have a subject called “${name}”.`);
    const subject = {
      id: nextId(db),
      userId: user.id,
      name,
      emoji: (body.emoji || '').trim() || null,
      colour: (body.colour || '').trim() || null,
      archived: 0,
    };
    db.subjects.push(subject);
    save(db);
    return { subject: subjectPublic(subject) };
  },

  'GET /api/subjects': (db, _body, token) => {
    const user = userFromToken(db, token);
    const subjects = db.subjects
      .filter((s) => s.userId === user.id && !s.archived)
      .map((s) => ({
        ...subjectPublic(s),
        topics: db.topics
          .filter((t) => t.subjectId === s.id && !t.archived)
          .map((t) => ({
            ...topicPublic(t),
            reviews: db.reviews
              .filter((r) => r.topicId === t.id)
              .map((r) => ({
                reviewedDate: r.reviewedDate,
                confidence: r.confidence,
                evidence: r.evidence,
                reflection: r.reflection,
                nextDue: r.nextDue,
              })),
          })),
      }));
    return { subjects };
  },

  'POST /api/topics': (db, body, token) => {
    const user = userFromToken(db, token);
    const name = requireStr(body.name, 'topic name');
    const subject = db.subjects.find(
      (s) => s.id === body.subjectId && s.userId === user.id && !s.archived,
    );
    if (!subject) fail('That subject could not be found.', 404);
    const topic = {
      id: nextId(db),
      subjectId: subject.id,
      name,
      emoji: (body.emoji || '').trim() || null,
      standardNumber: (body.standardNumber || '').trim() || null,
      reviewCount: 0,
      nextDue: null,
      archived: 0,
    };
    db.topics.push(topic);
    save(db);
    return { topic: topicPublic(topic) };
  },

  // Log a spaced-repetition review: advance the interval and store the optional
  // accountability fields (evidence + reflection). Confidence is recorded but,
  // per the spec, never changes the schedule.
  'POST /api/log-review': (db, body, token) => {
    const user = userFromToken(db, token);
    const topic = db.topics.find((t) => t.id === body.topicId && !t.archived);
    const subject =
      topic && db.subjects.find((s) => s.id === topic.subjectId && s.userId === user.id);
    if (!topic || !subject) fail('That topic could not be found.', 404);

    const count = (topic.reviewCount || 0) + 1;
    const interval = intervalFor(count);
    const reviewedDate = todayISO();
    const nextDue = addDaysISO(reviewedDate, interval);
    topic.reviewCount = count;
    topic.nextDue = nextDue;

    const review = {
      id: nextId(db),
      topicId: topic.id,
      reviewedDate,
      confidence: (body.confidence || '').trim() || null,
      evidence: (body.evidence || '').trim() || null, // accountability field
      reflection: (body.reflection || '').trim() || null, // accountability field
      interval,
      nextDue,
    };
    db.reviews.push(review);
    save(db);
    return { topic: topicPublic(topic), review };
  },
};

// Same signature the real api() uses internally; token is passed in so this
// module stays decoupled from api.js (no circular import).
async function mockApi(method, path, body, token) {
  await new Promise((r) => setTimeout(r, LATENCY_MS));
  // trace(`mock: handling ${method} ${path}`);  // debug trace (disabled in prototype)
  const handler = routes[`${method} ${path}`];
  if (!handler) fail('Not found.', 404);
  return handler(load(), body || {}, token);
}

/* ── js/api.js ── */
// Server communication — token storage + a thin fetch() wrapper.


const getToken = () => localStorage.getItem(TOKEN_KEY);
const setToken = (t) => localStorage.setItem(TOKEN_KEY, t);
const clearToken = () => localStorage.removeItem(TOKEN_KEY);

const REQUEST_TIMEOUT_MS = 10000;

// Call the API. Adds the Bearer token, sends/receives JSON, times out if the
// server is unreachable/slow, and throws an Error (with .status) carrying the
// server's friendly message on failure.
//
// In front-end-only mode (config USE_MOCK) it routes to an in-browser mock with
// the same contract instead of fetching — the rest of the app is unchanged.
async function api(method, path, body) {
  // trace(`api: ${method} ${path}`, USE_MOCK ? '→ MOCK backend' : '→ REAL backend (fetch)');  // debug trace (disabled in prototype)

  // ── Mock path (front-end only, ?mock or no real API configured) ──
  if (USE_MOCK) {
    /* mockApi is bundled in scope */
    try {
      const data = await mockApi(method, path, body, getToken());
      // trace(`api: ${method} ${path} ← OK (mock)`);  // debug trace (disabled in prototype)
      return data;
    } catch (e) {
      // trace(`api: ${method} ${path} ✗ ${e.status} (mock)`, e.message);  // debug trace (disabled in prototype)
      throw e;
    }
  }

  // ── Real path (Flask) ──
  const opts = { method, headers: {} };
  const tok = getToken();
  if (tok) opts.headers['Authorization'] = 'Bearer ' + tok;
  if (body !== undefined) {
    opts.headers['Content-Type'] = 'application/json';
    opts.body = JSON.stringify(body);
  }

  // Abort the request if it stalls, so the UI never hangs on a dead server.
  const ac = new AbortController();
  opts.signal = ac.signal;
  const timer = setTimeout(() => ac.abort(), REQUEST_TIMEOUT_MS);

  let res;
  try {
    res = await fetch(API_BASE + path, opts);
  } catch (e) {
    const msg =
      e.name === 'AbortError'
        ? 'The server took too long to respond. Please try again.'
        : "Couldn't reach the server. Check your connection and try again.";
    // trace(`api: ${method} ${path} ✗ network/timeout`, e.name);  // debug trace (disabled in prototype)
    const err = new Error(msg);
    err.status = 0; // network/timeout, not an HTTP status
    throw err;
  } finally {
    clearTimeout(timer);
  }

  let data = null;
  try {
    data = await res.json();
  } catch {
    /* an empty body is fine */
  }

  if (!res.ok) {
    // trace(`api: ${method} ${path} ✗ ${res.status}`, data && data.error);  // debug trace (disabled in prototype)
    const err = new Error((data && data.error) || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  // trace(`api: ${method} ${path} ← ${res.status} OK`);  // debug trace (disabled in prototype)
  return data;
}

/* ── js/screens/log-review.js ── */
// Log Review modal — the accountability heart of the app.
//
// Opened from the priorities feed (dashboard) and the subject-detail screen.
// Collects: confidence (recorded, never changes the schedule — per the spec),
// Evidence of Learning, and Reflection. On submit it calls POST /api/log-review
// then runs the caller's onDone() so the screen behind it refreshes.


// Confidence options — encouraging, non-judgemental language (per the tone rules).
const CONFIDENCE = [
  { key: 'shaky', label: 'Need more time' },
  { key: 'okay', label: 'Getting there' },
  { key: 'solid', label: 'Pretty well' },
];

let pending = null; // { topicId, onDone } for the currently-open modal

function openLogReview(topic, onDone) {
  // trace('log-review: open modal', { topicId: topic.id, name: topic.name });  // debug trace (disabled in prototype)
  pending = { topicId: topic.id, onDone };
  openModalFromHTML(`
    <div class="modal-card">
      <h2>Log a review</h2>
      <p class="modal-sub">${icon('circle-check-big', { size: 16 })} ${esc(topic.name)}</p>

      <div class="field">
        <label>How well did it go?</label>
        <div class="confidence-row" id="lr-confidence">
          ${CONFIDENCE.map(
            (c, i) =>
              `<button type="button" class="conf-pill${i === 1 ? ' active' : ''}" data-conf="${c.key}">${esc(c.label)}</button>`,
          ).join('')}
        </div>
      </div>

      <div class="field">
        <label for="lr-evidence">Evidence of Learning</label>
        <textarea class="input" id="lr-evidence" rows="3" placeholder="You can paste a key formula, list main points you revised, or describe what you did (notes, questions answered, etc.) or attach a Google Docs link"></textarea>
        <div class="lr-attach">
          <button type="button" class="btn btn-ghost btn-sm" data-action="lr-attach">${icon('plus', { size: 14 })} Attach file / photo</button>
          <span id="lr-attach-name" class="muted small"></span>
          <input type="file" id="lr-file" class="hidden" accept="image/*,.pdf,.doc,.docx">
        </div>
      </div>

      <div class="field">
        <label for="lr-reflection">Reflection</label>
        <textarea class="input" id="lr-reflection" rows="3" placeholder="You can write: One thing you understood better / One question you still have / What areas do you need to improve?"></textarea>
      </div>

      <p class="modal-note">These are just optional but they helps build real understanding and long-term retention to support your learning</p>

      <div class="modal-actions">
        <button class="btn btn-ghost" data-action="modal-cancel">Cancel</button>
        <button class="btn btn-primary" data-action="lr-submit">Log review</button>
      </div>
    </div>
  `);

  // Confidence pills: a small local listener (this markup only lives while open).
  const row = $('#lr-confidence');
  row.addEventListener('click', (e) => {
    const b = e.target.closest('[data-conf]');
    if (!b) return;
    row.querySelectorAll('.conf-pill').forEach((p) => p.classList.remove('active'));
    b.classList.add('active');
    // trace('log-review: confidence →', b.dataset.conf);  // debug trace (disabled in prototype)
  });
}

// Front-end-only file attach: shows the chosen filename (no upload backend yet).
function attachFile() {
  const input = $('#lr-file');
  input.onchange = () => {
    const f = input.files && input.files[0];
    $('#lr-attach-name').textContent = f ? `Attached: ${f.name}` : '';
    // trace('log-review: file attached', f && f.name);  // debug trace (disabled in prototype)
  };
  input.click();
}

async function submitLogReview(btn) {
  if (!pending) return;
  const confidence = $('#lr-confidence .conf-pill.active')?.dataset.conf || 'okay';
  const evidence = $('#lr-evidence').value.trim();
  const reflection = $('#lr-reflection').value.trim();
  // trace('log-review: submit → POST /api/log-review', {  // debug trace (disabled in prototype)
    topicId: pending.topicId,
    confidence,
    hasEvidence: !!evidence,
    hasReflection: !!reflection,
  });
  try {
    await withPending(btn, 'Saving…', () =>
      api('POST', '/api/log-review', {
        topicId: pending.topicId,
        confidence,
        evidence,
        reflection,
      }),
    );
    const done = pending.onDone;
    pending = null;
    closeModal();
    toast('Review logged — nice work!');
    if (done) await done(); // refresh the screen behind the modal
  } catch (e) {
    // trace('log-review: submit FAILED', e.message);  // debug trace (disabled in prototype)
    toast(e.message || 'Could not log review');
  }
}

/* ── js/screens/add.js ── */
// Add-Subject and Add-Topic modals — reachable from the dashboard, the subjects
// panel, and the subject-detail screen. Replaces the old window.prompt() so adding
// works consistently and looks like the rest of the app.
//
// FLOW: a button (data-action="add-subject" / "add-topic") → open…() shows a modal
// → the submit button (add-subject-submit / add-topic-submit, dispatched by main.js)
// → POST /api/subjects or /api/topics → onDone() refreshes the screen behind it.


// Common NCEA subjects offered as a datalist (still free-type-able).
const COMMON = ['English', 'Mathematics', 'Biology', 'Chemistry', 'Physics', 'History', 'Geography', 'Economics'];

let pending = null; // { onDone, subjectId? }

function showErr(msg) {
  const err = $('#add-err');
  err.textContent = msg;
  err.classList.remove('hidden');
}

function openAddSubject(onDone) {
  // trace('add: open Add Subject modal');  // debug trace (disabled in prototype)
  pending = { onDone };
  openModalFromHTML(`
    <div class="modal-card">
      <h2>Add subject</h2>
      <p class="modal-sub">Pick a common NCEA subject or type your own.</p>
      <div class="field">
        <label for="add-subj">Subject</label>
        <input class="input" id="add-subj" list="add-subj-list" placeholder="e.g. Biology" autocomplete="off">
        <datalist id="add-subj-list">${COMMON.map((s) => `<option value="${s}"></option>`).join('')}</datalist>
      </div>
      <p class="error-msg hidden" id="add-err"></p>
      <div class="modal-actions">
        <button class="btn btn-ghost" data-action="modal-cancel">Cancel</button>
        <button class="btn btn-primary" data-action="add-subject-submit">Add subject</button>
      </div>
    </div>`);
  setTimeout(() => $('#add-subj')?.focus(), 30);
}

async function submitAddSubject(btn) {
  const name = $('#add-subj').value.trim();
  if (!name) return showErr('Please type a subject name.');
  try {
    // trace('add: POST /api/subjects', { name });  // debug trace (disabled in prototype)
    await withPending(btn, 'Adding…', () => api('POST', '/api/subjects', { name }));
    const done = pending?.onDone;
    pending = null;
    closeModal();
    toast('Subject added');
    if (done) await done();
  } catch (e) {
    showErr(e.message || 'Could not add subject.');
  }
}

function openAddTopic(subjectId, subjectName, onDone) {
  // trace('add: open Add Topic modal', { subjectId, subjectName });  // debug trace (disabled in prototype)
  pending = { onDone, subjectId };
  openModalFromHTML(`
    <div class="modal-card">
      <h2>Add topic</h2>
      <p class="modal-sub">${subjectName ? `to ${esc(subjectName)}` : ''}</p>
      <div class="field">
        <label for="add-topic">Topic name</label>
        <input class="input" id="add-topic" placeholder="e.g. Photosynthesis" autocomplete="off">
      </div>
      <div class="field">
        <label for="add-std">Standard number <span class="muted">(optional)</span></label>
        <input class="input" id="add-std" placeholder="e.g. AS 91156" autocomplete="off">
      </div>
      <p class="error-msg hidden" id="add-err"></p>
      <div class="modal-actions">
        <button class="btn btn-ghost" data-action="modal-cancel">Cancel</button>
        <button class="btn btn-primary" data-action="add-topic-submit">Add topic</button>
      </div>
    </div>`);
  setTimeout(() => $('#add-topic')?.focus(), 30);
}

async function submitAddTopic(btn) {
  const name = $('#add-topic').value.trim();
  const standardNumber = $('#add-std').value.trim();
  if (!name) return showErr('Please type a topic name.');
  try {
    // trace('add: POST /api/topics', { subjectId: pending?.subjectId, name });  // debug trace (disabled in prototype)
    await withPending(btn, 'Adding…', () =>
      api('POST', '/api/topics', { subjectId: Number(pending.subjectId), name, standardNumber }),
    );
    const done = pending?.onDone;
    pending = null;
    closeModal();
    toast('Topic added');
    if (done) await done();
  } catch (e) {
    showErr(e.message || 'Could not add topic.');
  }
}

/* ── js/screens/dashboard.js ── */
// Dashboard (#screen-dashboard) — the homepage. Two tabs, per the mockups:
//   • Priorities     — today's review feed + a "Your subjects" side panel.
//   • Subject Details — a coverage-bar summary card per subject.
// Plus the intro cards (greeting + coverage). All data comes from GET /api/subjects;
// the priority feed + coverage are computed client-side in schedule.js.
//
// ── FULL FLOW (what happens, in order — turn on with ?debug=1 to watch) ──────
//   1. router.route() sees #dashboard → calls renderDashboard().
//   2. renderDashboard() → api('GET','/api/subjects') → (mock or Flask) returns
//      subjects[], each with topics[] (reviewCount, nextDue, reviews[]).
//   3. schedule.buildPriorities(subjects) ranks topics (overdue→due→new, capped 5);
//      schedule.coverageOf(topics) computes each %.
//   4. The active tab renders — prioritiesTab() (feed + subjects panel) or subjectsTab().
//   5. Clicks are dispatched by main.js (event delegation) → where they go next:
//        dash-tab      → setDashTab(tab) → renderDashboard() re-renders this screen
//        open-log      → main.js finds the topic → openLogReview() modal →
//                        submit → POST /api/log-review → route() refreshes the screen
//        view-subject  → navigate('#subject-<id>') → router → renderSubjectDetail()


let dashTab = 'priorities'; // remembered across re-renders

function setDashTab(tab) {
  dashTab = tab;
  // trace('dashboard: tab →', tab);  // debug trace (disabled in prototype)
  renderDashboard();
}

async function renderDashboard() {
  // trace('dashboard: render (tab=' + dashTab + ')');  // debug trace (disabled in prototype)
  const root = $('#screen-dashboard');
  const name = esc(state?.currentUser?.name || 'there');

  const { subjects } = await api('GET', '/api/subjects');
  const allTopics = subjects.flatMap((s) => s.topics);
  const coverage = coverageOf(allTopics);
  const reviewed = allTopics.filter((t) => (t.reviewCount || 0) >= 1).length;

  root.innerHTML = `
    <div class="dashboard">
      <div class="intro-cards">
        <div class="intro-card intro-greeting">
          <span class="intro-icon">${icon('hand', { size: 26 })}</span>
          <h1 class="intro-name">Kia ora (Hello), ${name}</h1>
        </div>
        <div class="intro-card intro-stat">
          <div class="intro-pct">${coverage}%</div>
          <div>
            <p class="intro-stat-label">Coverage</p>
            <p class="intro-stat-sub">${reviewed} of ${allTopics.length} topics reviewed</p>
          </div>
        </div>
      </div>

      <div class="dash-tabs">
        <button class="dash-tab${dashTab === 'priorities' ? ' active' : ''}" data-action="dash-tab" data-tab="priorities">Priorities</button>
        <button class="dash-tab${dashTab === 'subjects' ? ' active' : ''}" data-action="dash-tab" data-tab="subjects">Subject Details</button>
      </div>

      ${dashTab === 'priorities' ? prioritiesTab(subjects) : subjectsTab(subjects)}

      <p class="wellbeing-footer">
        Schools and exams can be quite overwhelming for some people. Do you need someone to talk? Youthline — 0800 376 633 or text 234 can give you great support.
      </p>
    </div>`;
}

function prioritiesTab(subjects) {
  if (!subjects.length) {
    return `<div class="empty-state">
        <p class="dashboard-sub">Let's add your first subject to get started.</p>
        <button class="btn btn-primary" data-action="add-subject">${icon('plus', { size: 15 })} Add subject</button>
      </div>`;
  }
  // Left column: today's review feed. Right column: the "Your subjects" panel.
  const { shown, moreCount, overdue, dueToday } = buildPriorities(subjects, 5);
  // trace('dashboard: prioritiesTab', { shown: shown.length, overdue, dueToday, moreCount });  // debug trace (disabled in prototype)
  const feed = shown.length
    ? `<p class="feed-summary">${overdue} overdue, ${dueToday} due today</p>
       ${shown.map(priorityCard).join('')}
       ${moreCount ? `<p class="more-when-ready">+${moreCount} more topics when you're ready</p>` : ''}`
    : `<p class="dashboard-sub">Nothing due right now — you're all caught up. Nice work!</p>`;
  return `
    <div class="dash-cols">
      <div class="feed-col">${feed}</div>
      ${subjectsPanel(subjects)}
    </div>`;
}

// The "Your subjects" panel that sits BESIDE the priorities feed (mockup 1).
function subjectsPanel(subjects) {
  // trace('dashboard: subjectsPanel', subjects.length, 'subjects');  // debug trace (disabled in prototype)
  return `
    <aside class="subjects-panel">
      <h3 class="sp-title">Your subjects</h3>
      ${subjects.map(subjectPanelRow).join('')}
      <button class="btn btn-soft btn-block" data-action="add-subject">${icon('plus', { size: 15 })} Add subject</button>
    </aside>`;
}

function subjectPanelRow(subject) {
  const cov = coverageOf(subject.topics || []);
  return `
    <div class="sp-row">
      <div class="sp-head" data-action="view-subject" data-subject-id="${subject.id}">
        <span class="sp-icon">${icon(subjectIcon(subject.name), { size: 18 })}</span>
        <span class="sp-name">${esc(subject.name)}</span>
        <span class="sp-pct">${cov}%</span>
      </div>
      <div class="progress"><span class="progress-fill" style="width:${cov}%"></span></div>
      <button class="sp-addtopic" data-action="add-topic" data-subject-id="${subject.id}" data-subject-name="${esc(subject.name)}">+ Add topics</button>
    </div>`;
}

function priorityCard(item) {
  const badge = statusBadge(item);
  return `
    <div class="priority-card">
      <div class="pc-left">
        <span class="subject-tag">${esc(item.subjectName)}</span>
        <div class="pc-topic">${esc(item.name)}${item.standardNumber ? ` <span class="std">${esc(item.standardNumber)}</span>` : ''}</div>
        <div class="pc-meta">${item.reviewCount ? `Reviewed ${item.reviewCount}× · ready for review` : 'New topic — first review'}</div>
        <span class="status-badge ${badge.cls}">${badge.label}</span>
      </div>
      <button class="btn btn-soft" data-action="open-log" data-topic-id="${item.id}">${icon('circle-check-big', { size: 15 })} Log review</button>
    </div>`;
}

function subjectsTab(subjects) {
  if (!subjects.length) {
    return `<div class="empty-state">
        <p>You don't have any subjects yet but that's okay. You can add them any time=)</p>
        <button class="btn btn-primary" data-action="add-subject">${icon('plus', { size: 15 })} Add subject</button>
      </div>`;
  }
  return `${subjects.map(subjectSummaryCard).join('')}
    <button class="btn btn-soft btn-block add-subjects-btn" data-action="add-subject">${icon('plus', { size: 15 })} Add subjects</button>`;
}

function subjectSummaryCard(subject) {
  const topics = subject.topics || [];
  const cov = coverageOf(topics);
  const reviewed = topics.filter((t) => (t.reviewCount || 0) >= 1).length;
  return `
    <div class="subject-summary" data-action="view-subject" data-subject-id="${subject.id}">
      <span class="ss-icon">${icon(subjectIcon(subject.name), { size: 26 })}</span>
      <div class="ss-body">
        <div class="ss-name">${esc(subject.name)}</div>
        <div class="ss-meta">You have reviewed ${reviewed} of ${topics.length} topics</div>
        <div class="progress"><span class="progress-fill" style="width:${cov}%"></span></div>
      </div>
      <div class="ss-pct">${cov}%</div>
      <button class="btn btn-soft btn-sm" data-action="view-subject" data-subject-id="${subject.id}">View More</button>
    </div>`;
}

/* ── js/screens/subject-detail.js ── */
// Subject-detail screen (#screen-subject) — mockup 3.
//
// Shows one subject's coverage, today's priority topic, and every topic with its
// review count, average confidence, expandable history, and a Log review button.
// Also the Internal (assessment) mode toggle. Reached via hash #subject-<id>.


const CONF_LABEL = { shaky: 'Need more time', okay: 'Getting there', solid: 'Pretty well' };
const INTERNAL_KEY = 'nrn_internal_subjects'; // front-end-only assessment-mode flags

const internalSet = () => new Set(JSON.parse(localStorage.getItem(INTERNAL_KEY) || '[]'));
function toggleInternal(id) {
  const s = internalSet();
  s.has(id) ? s.delete(id) : s.add(id);
  localStorage.setItem(INTERNAL_KEY, JSON.stringify([...s]));
  // trace('subject-detail: internal mode toggled', id, s.has(id));  // debug trace (disabled in prototype)
  return s.has(id);
}
function isInternal(id) {
  return internalSet().has(id);
}

function avgConfidence(topic) {
  const last = (topic.reviews || []).filter((r) => r.confidence).slice(-1)[0];
  return last ? CONF_LABEL[last.confidence] || last.confidence : null;
}

function topicRow(topic, isPriority = false) {
  const badge = statusBadge(topic);
  const pct = topic.reviewCount ? Math.min(100, topic.reviewCount * 25) : 0;
  const conf = avgConfidence(topic);
  const history = (topic.reviews || []).length
    ? `<details class="topic-history"><summary>View history (${topic.reviews.length})</summary>
         <ul>${topic.reviews
           .map(
             (r, i) =>
               `<li>R${i + 1} · ${esc(r.reviewedDate)}${r.confidence ? ` · ${esc(CONF_LABEL[r.confidence] || r.confidence)}` : ''} → due ${esc(r.nextDue)}${
                 r.reflection ? `<span class="hist-note">“${esc(r.reflection)}”</span>` : ''
               }</li>`,
           )
           .join('')}</ul></details>`
    : '';
  return `
    <div class="topic-row${isPriority ? ' topic-priority' : ''}">
      <div class="topic-main">
        <div class="topic-name">${esc(topic.name)}${topic.standardNumber ? ` <span class="std">${esc(topic.standardNumber)}</span>` : ''}</div>
        <div class="topic-meta">${topic.reviewCount ? `Reviewed ${topic.reviewCount}× · ${pct}%` : 'Not yet reviewed'}${conf ? ` · <span class="conf-tag">${esc(conf)}</span>` : ''}</div>
        ${history}
      </div>
      <div class="topic-side">
        <button class="btn btn-soft btn-sm" data-action="open-log" data-topic-id="${topic.id}">${icon('circle-check-big', { size: 15 })} Log review</button>
        <span class="status-badge ${badge.cls}">${badge.label}</span>
      </div>
    </div>`;
}

async function renderSubjectDetail(subjectId) {
  // trace('subject-detail: render', subjectId);  // debug trace (disabled in prototype)
  const root = $('#screen-subject');
  const { subjects } = await api('GET', '/api/subjects');
  const subject = subjects.find((s) => String(s.id) === String(subjectId));
  if (!subject) {
    navigate('#dashboard');
    return;
  }

  const topics = subject.topics || [];
  const cov = coverageOf(topics);
  const reviewed = topics.filter((t) => (t.reviewCount || 0) >= 1).length;
  // Today's priority = the most urgent topic: overdue > due > new, then most
  // overdue first. A topic that's already scheduled ahead (ok) is never "today's".
  const RANK = { overdue: 3, due: 2, new: 1, ok: 0 };
  const sorted = [...topics].sort((a, b) => {
    const ra = statusOf(a);
    const rb = statusOf(b);
    return RANK[rb.status] - RANK[ra.status] || rb.days - ra.days;
  });
  const priority = sorted[0] && statusOf(sorted[0]).status !== 'ok' ? sorted[0] : null;
  const internal = isInternal(subject.id);

  root.innerHTML = `
    <div class="subject-detail">
      <button class="link-back" data-action="nav-dashboard">${icon('log-out', { size: 16, cls: 'flip' })} Back</button>

      <div class="sd-head">
        <h1 class="sd-title">${icon(subjectIcon(subject.name), { size: 30, cls: 'subject-icon' })} ${esc(subject.name)}</h1>
        <div class="sd-actions">
          <button class="btn btn-soft btn-sm" data-action="add-topic" data-subject-id="${subject.id}" data-subject-name="${esc(subject.name)}">${icon('plus', { size: 15 })} Add topics</button>
        </div>
      </div>

      <p class="sd-coverage">Coverage: ${cov}% (${reviewed} of ${topics.length} topics reviewed)</p>
      <div class="progress"><span class="progress-fill" style="width:${cov}%"></span></div>

      ${internal ? '<div class="internal-banner">Internal mode is on — this subject is paused while you focus on the assessment.</div>' : ''}

      ${
        priority
          ? `<h3 class="sd-section">Today's priority</h3>${topicRow(priority, true)}`
          : ''
      }

      <h3 class="sd-section">All topics</h3>
      ${topics.length ? topics.map((t) => topicRow(t)).join('') : '<p class="muted small">No topics yet — add some to get started.</p>'}

      <button class="btn btn-internal" data-action="toggle-internal" data-subject-id="${subject.id}">
        ${internal ? 'Stop' : 'Start'} Internal mode for ${esc(subject.name)}
      </button>
    </div>`;
}

// Wired from main.js delegated handler.
function onToggleInternal(id) {
  toggleInternal(Number(id));
  route();
}
async function onAddTopic(subjectId) {
  const name = window.prompt('New topic name'); // simple for now
  if (!name || !name.trim()) return;
  try {
    await api('POST', '/api/topics', { subjectId: Number(subjectId), name: name.trim() });
    toast('Topic added');
    route();
  } catch (e) {
    toast(e.message || 'Could not add topic');
  }
}

/* ── js/screens/settings.js ── */
// Settings screen (#screen-settings) — account summary + the daily review cap.
// The cap is UI-only for now (no backend yet); logout lives here too.


async function renderSettings() {
  // trace('settings: render');  // debug trace (disabled in prototype)
  const root = $('#screen-settings');
  const u = state.currentUser || {};
  root.innerHTML = `
    <div class="settings">
      <button class="link-back" data-action="nav-dashboard">${icon('log-out', { size: 16, cls: 'flip' })} Back</button>
      <h1 class="settings-title">${icon('settings', { size: 24 })} Settings</h1>

      <div class="settings-card">
        <div class="setting-row"><span>Name</span><strong>${esc(u.name || '')}</strong></div>
        <div class="setting-row"><span>Email</span><strong>${esc(u.email || '')}</strong></div>
        <div class="setting-row"><span>Year level</span><strong>Year ${esc(String(u.yearLevel || 12))}</strong></div>
      </div>

      <div class="settings-card">
        <div class="field">
          <label for="set-cap">Daily review cap</label>
          <select class="input select-input" id="set-cap">
            ${[3, 4, 5, 6, 7, 8].map((n) => `<option${n === 5 ? ' selected' : ''}>${n}</option>`).join('')}
          </select>
          <p class="muted small">The most topics we'll suggest each day, so it never feels overwhelming.</p>
        </div>
      </div>

      <button class="btn btn-danger btn-block" data-action="do-logout">${icon('log-out', { size: 16 })} Log out</button>
    </div>`;
}

/* ── js/screens/auth.js ── */
// Auth screen (#screen-auth) — login + create-account forms.
//
// Responsibilities: read the form inputs, run cheap client-side validation, call
// the auth API (mock or Flask via api()), and on success store the JWT and route
// to the dashboard. Every failure surfaces as a friendly message in the screen's
// `.error-msg` slot — never a blank screen or a raw error.
//
// Behaviour is attached through `data-action` attributes, dispatched by the single
// delegated click handler in main.js (e.g. data-action="do-login" → doLogin), so
// the HTML stays free of inline JS. Full event flow: docs/design/auth-screen.md.
//
// DEBUG: this file is traced end-to-end. Open the app with ?debug=1 and watch the
// Console to follow each step. trace(...) is console.log gated by that flag.


// Mirrors the backend's minimum; the server re-checks, this is just fast feedback.
/* dedup: MIN_PASSWORD_LEN (already declared above) */

// Reset the screen to a clean slate every time it is (re)entered: default to the
// login tab, clear all fields, hide any leftover error. Called by route().
function hydrateAuth() {
  // trace('auth: hydrateAuth() — reset fields, default to login tab');  // debug trace (disabled in prototype)
  setAuthMode('login');
  ['login-email', 'login-pw', 'signup-name', 'signup-email', 'signup-pw', 'signup-pw2'].forEach(
    (id) => {
      const el = document.getElementById(id);
      if (el) el.value = '';
    },
  );
  hide($('#login-err'));
  hide($('#signup-err'));
}

// Switch between the login and signup tabs: highlight the active tab and reveal
// the matching form (the other is hidden). Records the mode so the Enter-key
// shortcut in main.js knows which form to submit.
function setAuthMode(mode) {
  // trace('auth: setAuthMode →', mode);  // debug trace (disabled in prototype)
  state.authMode = mode;
  $$('.auth-tabs button').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.mode === mode);
  });
  $('#auth-login').classList.toggle('hidden', mode !== 'login');
  $('#auth-signup').classList.toggle('hidden', mode !== 'signup');
}

// Handle a "Sign in" click. `btn` is the clicked button so withPending() can
// disable it and show a pending label for the duration of the request (which both
// gives feedback and prevents a double-submit).
async function doLogin(btn) {
  // trace('auth: doLogin() start');  // debug trace (disabled in prototype)
  const err = $('#login-err');
  hide(err);

  // Layer 1 — client-side guard: avoid a pointless round-trip on empty input.
  const email = $('#login-email').value.trim();
  const password = $('#login-pw').value;
  if (!email || !password) {
    // trace('auth: doLogin VALIDATION FAILED — empty email or password');  // debug trace (disabled in prototype)
    err.textContent = 'You havent enter your gmail or password.';
    show(err);
    return;
  }

  // Tip: an alert() is a quick "freeze and look" probe, but it BLOCKS the page —
  // never leave one in shipped code. Uncomment to try it once, then remove:
  //   alert('about to call the login API for ' + email);

  try {
    // Layer 2 — the backend authenticates. On success it returns { token, user }.
    // trace('auth: doLogin → POST /api/auth/login', { email }); // never log the password  // debug trace (disabled in prototype)
    const r = await withPending(btn, 'Signing in…', () =>
      api('POST', '/api/auth/login', { email, password }),
    );
    // trace('auth: doLogin OK ← user:', r.user, '→ setToken + go #dashboard');  // debug trace (disabled in prototype)
    setToken(r.token); // persist the JWT (localStorage: ncea_token)
    state.currentUser = r.user;
    navigate('#dashboard');
  } catch (e) {
    // 401 (bad credentials), 400, or a network/timeout error — all friendly here.
    // trace('auth: doLogin FAILED', { status: e.status, message: e.message });  // debug trace (disabled in prototype)
    err.textContent = e.message || 'Your login process failed. Please try again:(';
    show(err);
  }
}

// Handle a "Create account" click. Runs three client-side guards (required fields,
// passwords match, min length) BEFORE the network call; the backend still
// re-validates everything and owns duplicate-email detection (→ 400).
async function doSignup(btn) {
  // trace('auth: doSignup() start');  // debug trace (disabled in prototype)
  const err = $('#signup-err');
  hide(err);

  const name = $('#signup-name').value.trim();
  const email = $('#signup-email').value.trim();
  const password = $('#signup-pw').value;
  const password2 = $('#signup-pw2').value;
  const yearLevel = $('#signup-year').value;

  if (!name || !email || !password) {
    // trace('auth: doSignup VALIDATION FAILED — missing required field');  // debug trace (disabled in prototype)
    err.textContent = 'You havent fill in all the required field';
    show(err);
    return;
  }
  if (password !== password2) {
    // trace('auth: doSignup VALIDATION FAILED — passwords do not match');  // debug trace (disabled in prototype)
    err.textContent = "Passwords don't match.";
    show(err);
    return;
  }
  if (password.length < MIN_PASSWORD_LEN) {
    // trace('auth: doSignup VALIDATION FAILED — password too short');  // debug trace (disabled in prototype)
    err.textContent = `Your password must be at least ${MIN_PASSWORD_LEN} characters.`;
    show(err);
    return;
  }

  try {
    // New accounts come back with onboarding_done = 0, so route() will send the
    // user to onboarding (not the dashboard) on the next pass.
    // trace('auth: doSignup → POST /api/auth/signup', { name, email, yearLevel });  // debug trace (disabled in prototype)
    const r = await withPending(btn, 'Creating account…', () =>
      api('POST', '/api/auth/signup', { name, email, yearLevel, password }),
    );
    // trace('auth: doSignup OK ← user:', r.user, '→ setToken + go #dashboard');  // debug trace (disabled in prototype)
    setToken(r.token);
    state.currentUser = r.user;
    navigate('#dashboard');
  } catch (e) {
    // trace('auth: doSignup FAILED', { status: e.status, message: e.message });  // debug trace (disabled in prototype)
    err.textContent = e.message || 'Your signup process failed. Please try again:(';
    show(err);
  }
}

/* ── js/screens/onboarding.js ── */
// Onboarding screen — 3-step flow: welcome → add subject → add topics.


const ob = state.onboarding;

function hydrateOnboarding() {
  resetOnboarding();
  obRender();
}

function obRender() {
  // Progress dots.
  $$('#ob-dots .dot').forEach((d, i) => {
    d.classList.toggle('done', i + 1 < ob.step);
    d.classList.toggle('active', i + 1 === ob.step);
  });
  // Show only the current step.
  [1, 2, 3].forEach((n) => {
    document.getElementById('ob-step-' + n).classList.toggle('hidden', n !== ob.step);
  });
  // Wire the "Other" custom-subject toggle.
  const sel = $('#ob-subj-select');
  if (sel) {
    sel.onchange = () => {
      $('#ob-custom-field').classList.toggle('hidden', sel.value !== '__custom__');
    };
  }
  // Step 3: subject heading + chips.
  if (ob.step === 3) {
    $('#ob-subject-name').textContent = ob.createdSubject ? ob.createdSubject.name : 'your subject';
    renderObChips();
  }
}

function obNext() {
  ob.step = 2;
  obRender();
}

function renderObChips() {
  const wrap = $('#ob-topic-chips');
  if (!ob.addedTopics.length) {
    wrap.innerHTML =
      '<span class="muted small"> You dont have any  topics added yet. But you can add them later too.</span>';
    return;
  }
  wrap.innerHTML = ob.addedTopics
    .map(
      (name, i) =>
        `<span class="topic-chip">${esc(name)}
           <span class="chip-remove" data-ob-remove="${i}">✕</span>
         </span>`,
    )
    .join('');
  $$('#ob-topic-chips .chip-remove').forEach((x) => {
    x.onclick = () => {
      ob.addedTopics.splice(+x.dataset.obRemove, 1);
      renderObChips();
    };
  });
}

async function obAddSubject(btn) {
  const sel = $('#ob-subj-select');
  if (!sel.value) {
    toast('Pick a subject first');
    return;
  }
  // No emoji stored — the dashboard picks a Lucide icon from the subject name
  // (see icons.js subjectIcon). Options carry data-icon just for documentation.
  let name, colour;
  if (sel.value === '__custom__') {
    name = $('#ob-custom').value.trim();
    if (!name) {
      toast('Type a subject name');
      return;
    }
    colour = undefined;
  } else {
    const opt = sel.selectedOptions[0];
    name = sel.value;
    colour = opt.dataset.colour;
  }
  try {
    // trace('onboarding: obAddSubject → POST /api/subjects', { name });  // debug trace (disabled in prototype)
    const r = await withPending(btn, 'Adding…', () =>
      api('POST', '/api/subjects', { name, colour }),
    );
    ob.createdSubject = r.subject;
    ob.step = 3;
    obRender();
  } catch (e) {
    toast(e.message);
  }
}

function obAddTopic() {
  const input = $('#ob-topic-input');
  const name = input.value.trim();
  if (!name) return;
  ob.addedTopics.push(name);
  input.value = '';
  renderObChips();
  input.focus();
}

async function obFinish(btn) {
  try {
    await withPending(btn, 'Saving…', async () => {
      if (ob.createdSubject) {
        // trace('onboarding: obFinish → creating', ob.addedTopics.length, 'topics');  // debug trace (disabled in prototype)
        for (const name of ob.addedTopics) {
          await api('POST', '/api/topics', { subjectId: ob.createdSubject.id, name });
        }
      }
      await finishOnboarding();
    });
  } catch (e) {
    toast(e.message);
  }
}

async function obSkip() {
  await finishOnboarding();
}

async function finishOnboarding() {
  await api('PUT', '/api/user/onboarding');
  state.currentUser.onboarding_done = 1;
  resetOnboarding();
  navigate('#dashboard');
}

/* ── js/router.js ── */
// Hash router — decides which screen is visible based on auth + onboarding
// state and the current hash. Runs once on load and again on every hashchange.


const SCREENS = [
  'screen-auth',
  'screen-onboarding',
  'screen-dashboard',
  'screen-subject',
  'screen-settings',
];

function showScreen(id) {
  SCREENS.forEach((s) => {
    const el = document.getElementById(s);
    if (el) el.classList.toggle('hidden', s !== id);
  });
}

function navigate(hash) {
  if (location.hash === hash) route();
  else location.hash = hash;
}

async function route() {
  // The router decides which screen to show. Trace its inputs every time it runs.
  // trace('router: route()', { hash: location.hash || '#', hasToken: !!getToken() });  // debug trace (disabled in prototype)

  // No token → not logged in → show auth.
  if (!getToken()) {
    // trace('router: no token → showing AUTH screen');  // debug trace (disabled in prototype)
    state.currentUser = null;
    hide($('#topbar'));
    showScreen('screen-auth');
    hydrateAuth();
    return;
  }

  // Have a token but no user object yet → fetch it (token may be expired).
  if (!state.currentUser) {
    try {
      state.currentUser = (await api('GET', '/api/auth/me')).user;
    } catch {
      clearToken();
      return route();
    }
  }

  // Logged in but onboarding not finished → onboarding flow.
  if (!state.currentUser.onboarding_done) {
    // trace('router: logged in, onboarding not done → ONBOARDING screen');  // debug trace (disabled in prototype)
    hide($('#topbar'));
    showScreen('screen-onboarding');
    hydrateOnboarding();
    return;
  }
  // trace('router: logged in + onboarded → DASHBOARD');  // debug trace (disabled in prototype)

  // Fully logged in — show topbar and route by hash.
  show($('#topbar'));
  const hash = location.hash || '#dashboard';
  try {
    if (hash === '#settings') {
      showScreen('screen-settings');
      await renderSettings();
    } else if (hash.startsWith('#subject-')) {
      showScreen('screen-subject');
      await renderSubjectDetail(hash.slice('#subject-'.length));
    } else {
      showScreen('screen-dashboard');
      await renderDashboard();
    }
  } catch (e) {
    toast(e.message || 'Something went wrong');
  }
}

/* ── js/main.js ── */
// ✅
// Composition root — imports every screen handler, wires one delegated click
// listener + keyboard shortcuts, and starts the router. This is the only script
// the HTML loads (`<script type="module" src="js/main.js">`).
//import all these things from these files so i can use them

// Signal that the ES-module graph loaded and ran. The classic serve-guard in
// index.html checks this flag; if it's never set (e.g. opened via file://, where
// browsers block module imports) it shows a "serve me" help card instead of a
// blank page.
window.__NRN_BOOTED = true;

// ── Global click delegation ──
//hey browser, stad guard at top page-> run this everytime users click on screen. (e)= event -> info package
document.body.addEventListener('click', async (e) => { 
  // Let an open modal manage its own clicks first.
  if (e.target.closest('#modal-overlay')) {
    // Backdrop-click close is handled in dom.js. Here we only special-case Cancel,
    // then let real modal buttons (lr-submit, lr-attach) fall through to dispatch.
    if (e.target.closest('[data-action="modal-cancel"]')) {
      closeModal();
      return;
    }
  }

  const act = e.target.closest('[data-action]');
  if (!act) return;

  // STEP 1 of the flow: a click on a [data-action] element is dispatched here.
  // trace('main: click →', act.dataset.action + (act.dataset.mode ? ` (mode=${act.dataset.mode})` : ''));  // debug trace (disabled in prototype)

  try {
    switch (act.dataset.action) {
      // Auth
      case 'auth-tab':
        setAuthMode(act.dataset.mode);
        break;
      case 'do-login':
        await doLogin(act);
        break;
      case 'do-signup':
        await doSignup(act);
        break;

      // Onboarding
      case 'ob-next':
        obNext();
        break;
      case 'ob-add-subject':
        await obAddSubject(act);
        break;
      case 'ob-add-topic':
        obAddTopic();
        break;
      case 'ob-finish':
        await obFinish(act);
        break;
      case 'ob-skip':
        await obSkip();
        break;

      // Dashboard tabs / subject detail / log review (slice 2)
      case 'dash-tab':
        setDashTab(act.dataset.tab);
        break;
      case 'view-subject':
        navigate('#subject-' + act.dataset.subjectId);
        break;
      case 'open-log': {
        // Look the topic up fresh, then open the modal; refresh the screen on save.
        const tid = Number(act.dataset.topicId);
        const { subjects } = await api('GET', '/api/subjects');
        const topic = subjects.flatMap((s) => s.topics).find((t) => t.id === tid);
        if (topic) openLogReview(topic, route);
        break;
      }
      case 'lr-submit':
        await submitLogReview(act);
        break;
      case 'lr-attach':
        attachFile();
        break;
      case 'toggle-internal':
        onToggleInternal(act.dataset.subjectId);
        break;

      // Add subject / add topic (modals, refresh the screen on success)
      case 'add-subject':
        openAddSubject(route);
        break;
      case 'add-subject-submit':
        await submitAddSubject(act);
        break;
      case 'add-topic':
        openAddTopic(act.dataset.subjectId, act.dataset.subjectName, route);
        break;
      case 'add-topic-submit':
        await submitAddTopic(act);
        break;

      // Navigation
      case 'nav-dashboard':
        navigate('#dashboard');
        break;
      case 'nav-settings':
        navigate('#settings');
        break;
      case 'do-logout':
        try {
          await api('POST', '/api/auth/logout');
        } catch {
          /* logging out is best-effort */
        }
        clearToken();
        state.currentUser = null;
        navigate('#');
        route();
        break;
    }
  } catch (err) {
    toast(err.message || 'Something went wrong');
  }
});

// ── Keyboard shortcuts ──
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') {
    if ($('#modal-overlay').classList.contains('show')) closeModal();
    return;
  }
  // Enter submits the auth form.
  if (e.key === 'Enter' && !$('#screen-auth').classList.contains('hidden')) {
    // trace('main: Enter key submits the', state.authMode, 'form');  // debug trace (disabled in prototype)
    if (state.authMode === 'login') doLogin($('[data-action="do-login"]'));
    else doSignup($('[data-action="do-signup"]'));
  }
  // Enter adds a topic in onboarding step 3.
  if (e.key === 'Enter' && document.activeElement?.id === 'ob-topic-input') {
    obAddTopic();
  }
});

// ── Startup ──
window.addEventListener('hashchange', route);
route(); // modules are deferred, so the DOM is already parsed here.
hydrateIcons(); // replace every static [data-icon] element with its Lucide SVG
})();
