#!/usr/bin/env python3
"""Build a standalone 3-file frontend prototype: index.html + styles.css + app.js.

For mockup/prototype review with ONLY HTML/CSS/JS — no backend, no DB, no server.
HTML, CSS, and JS stay in SEPARATE files (the project's isolation rule), but:
  * the four css/*.css are concatenated into one styles.css, and
  * the ES modules are flattened into one classic app.js (no import/export), with
    the mock backend bundled in and on by default.
A classic <script src="app.js"> (not type="module") is what lets it open straight
from the filesystem (file://) — ES modules are blocked over file://.

Output: front-end/prototype/{index.html, styles.css, app.js}. It is a generated
artifact — edit the real source under front-end/js + front-end/css, then re-run
`task prototype`. No npm, no bundler — a plain-text transform.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FE = ROOT / "front-end"
OUT_DIR = FE / "prototype"

CSS_FILES = ["css/tokens.css", "css/base.css", "css/components.css", "css/screens.css"]

# Concatenation order. Only two constraints matter (everything else is hoisted
# function declarations sharing one scope): `state` must precede `onboarding`
# (it reads state.onboarding at load), and `main` must be last (it runs route()).
JS_FILES = [
    "js/config.js",
    "js/dom.js",
    "js/state.js",
    "js/api.mock.js",
    "js/api.js",
    "js/screens/dashboard.js",
    "js/screens/auth.js",
    "js/screens/onboarding.js",
    "js/router.js",
    "js/main.js",
]


def strip_module_syntax(src: str) -> str:
    """Remove import/export syntax and the dynamic mock import from one module."""
    src = src.replace(
        "const { mockApi } = await import('./api.mock.js');",
        "/* mockApi is bundled in scope */",
    )
    out = []
    in_multiline_import = False
    for line in src.splitlines():
        if in_multiline_import:
            if "from " in line or line.rstrip().endswith(";"):
                in_multiline_import = False
            continue
        if re.match(r"^import\b", line):
            if "from " not in line and "';" not in line:
                in_multiline_import = True  # `import {` on its own line
            continue
        if re.match(r"^export\s*\{", line):
            continue
        line = re.sub(r"^export\s+(async\s+function|function|const|let|class)\b", r"\1", line)
        out.append(line)
    return "\n".join(out)


def dedupe_top_level_consts(src: str) -> str:
    """Drop repeated top-level `const NAME = …;` (e.g. MIN_PASSWORD_LEN in two modules)."""
    seen: set[str] = set()
    out = []
    for line in src.splitlines():
        m = re.match(r"^(?:const|let)\s+([A-Za-z_$][\w$]*)\s*=.*;\s*$", line)
        if m:
            name = m.group(1)
            if name in seen:
                out.append(f"/* dedup: {name} (already declared above) */")
                continue
            seen.add(name)
        out.append(line)
    return "\n".join(out)


def build() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1) styles.css — the four token/base/component/screen sheets, concatenated.
    css = "\n".join(f"/* {f} */\n{(FE / f).read_text(encoding='utf-8')}" for f in CSS_FILES)
    (OUT_DIR / "styles.css").write_text(css, encoding="utf-8")

    # 2) app.js — ES modules flattened into one classic, IIFE-wrapped script.
    modules = "\n\n".join(
        f"/* ── {f} ── */\n{strip_module_syntax((FE / f).read_text(encoding='utf-8'))}"
        for f in JS_FILES
    )
    app_js = (
        "/* GENERATED by scripts/build-prototype.py — do not edit. */\n"
        "/* Standalone frontend prototype: mock backend bundled in, no server/DB. */\n"
        "(function () {\n'use strict';\n" + dedupe_top_level_consts(modules) + "\n})();\n"
    )
    (OUT_DIR / "app.js").write_text(app_js, encoding="utf-8")

    # 3) index.html — same markup, but linking the two local files (classic script).
    html = (FE / "index.html").read_text(encoding="utf-8")
    html = re.sub(r'[ \t]*<link rel="stylesheet"[^>]*>\n', "", html, count=4)
    html = html.replace(
        "</title>", '</title>\n  <link rel="stylesheet" href="styles.css">'
    )
    html = html.replace(
        '  <script type="module" src="js/main.js"></script>',
        '  <script src="app.js"></script>',
    )
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")

    rel = OUT_DIR.relative_to(ROOT)
    total = sum((OUT_DIR / f).stat().st_size for f in ("index.html", "styles.css", "app.js"))
    print(f"Wrote {rel}/ — index.html + styles.css + app.js ({total / 1024:.0f} KB).")
    print(f"Open {rel}/index.html directly in a browser (no server, no backend).")


if __name__ == "__main__":
    build()
