/* GENERATED by scripts/build-prototype.py — do not edit. */
/* Standalone frontend prototype: mock backend bundled in, no server/DB. */
(function () {
'use strict';
/* ── js/config.js ── */
// Configuration & constants.
//
// Split-origin setup: the API runs on a different origin to this static SPA,
// so calls use an absolute base URL. Override at runtime by setting
// `window.NRN_API_BASE` before the module scripts load (e.g. for deployment).
//
// Host port 5050 (not 5000): macOS AirPlay Receiver occupies 5000, so the API's
// published host port is 5050 (see docker-compose.yml). Keep this in sync with it.

const API_BASE = window.NRN_API_BASE || 'http://127.0.0.1:5050';

// Backend selection. The SPA defaults to an in-browser MOCK backend so it runs
// standalone for prototype/mockup review — only HTML/CSS/JS, no Flask, no DB.
// It switches to the real API when a real base URL is configured (deploy injects
// window.NRN_API_BASE) or you pass ?real=1. The mock mirrors the real API
// contract, so nothing else changes. See js/api.mock.js + docs/dev-and-test.md.
//   (default)  → mock        ?real=1 → real API        ?mock=1 → force mock
const _params = new URLSearchParams(window.location.search);
const USE_MOCK = _params.has('mock')
  ? true
  : _params.has('real')
    ? false
    : typeof window.NRN_USE_MOCK === 'boolean'
      ? window.NRN_USE_MOCK
      : !window.NRN_API_BASE; // no real API configured → mock

const TOKEN_KEY = 'ncea_token';

const DEFAULT_TOPIC_EMOJI = '📚';

/* ── js/dom.js ── */
// DOM helpers — selectors, show/hide, HTML escaping, toast, and modal plumbing.

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

function show(el) {
  if (el) el.classList.remove('hidden');
}
function hide(el) {
  if (el) el.classList.add('hidden');
}

// Escape user-supplied text before inserting into innerHTML (XSS-safe).
function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

let toastTimer = null;
function toast(msg) {
  const el = $('#toast');
  if (!el) return;
  el.textContent = msg;
  void el.offsetWidth; // force reflow so the transition re-fires
  el.classList.add('show');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => el.classList.remove('show'), 2200);
}

function openModalFromHTML(html) {
  const ov = $('#modal-overlay');
  ov.innerHTML = html;
  ov.classList.add('show');
  ov.onclick = (e) => {
    if (e.target === ov) closeModal();
  };
  return ov;
}

function closeModal() {
  const ov = $('#modal-overlay');
  ov.classList.remove('show');
  ov.onclick = null;
  setTimeout(() => {
    if (!ov.classList.contains('show')) ov.innerHTML = '';
  }, 220);
}

// Run an async action while disabling a button and showing pending text, so
// API calls never feel frozen. Restores the original label afterwards.
async function withPending(btn, pendingText, fn) {
  if (!btn) return fn();
  const original = btn.textContent;
  btn.disabled = true;
  btn.textContent = pendingText;
  try {
    return await fn();
  } finally {
    btn.disabled = false;
    btn.textContent = original;
  }
}

/* ── js/state.js ── */
// Central app state. A single mutable object so modules share one source of
// truth (ES module exports are live bindings — mutate properties, don't reassign).

const state = {
  currentUser: null, // { id, name, email, yearLevel, onboarding_done }
  authMode: 'login', // 'login' | 'signup'
  onboarding: {
    step: 1, // 1 | 2 | 3
    createdSubject: null, // { id, name, emoji, colour }
    addedTopics: [], // string[]
  },
};

function resetOnboarding() {
  state.onboarding.step = 1;
  state.onboarding.createdSubject = null;
  state.onboarding.addedTopics = [];
}

/* ── js/api.mock.js ── */
// In-browser mock backend — front-end-only dev (no Flask, no SQLite).
//
// Enabled by `?mock=1` (see config.js USE_MOCK). It mirrors the real API
// contract exactly — same request bodies, same response shapes, same status
// codes and friendly error messages — so the SPA can't tell the difference and
// switching to the real backend is just removing the flag.
//
// Data persists in localStorage (key `nrn_mock_db`) so reloads keep your state.
// Tokens are `mock.<userId>` (no real crypto — this is a dev stand-in only).

const DB_KEY = 'nrn_mock_db';
const MIN_PASSWORD_LEN = 4;
const MAX_NAME_LEN = 80;
const LATENCY_MS = 120; // a little delay so pending/disabled UI states are visible

function load() {
  try {
    return JSON.parse(localStorage.getItem(DB_KEY)) ?? blank();
  } catch {
    return blank();
  }
}
function blank() {
  return { users: [], subjects: [], topics: [], seq: 0 };
}
function save(db) {
  localStorage.setItem(DB_KEY, JSON.stringify(db));
}
function nextId(db) {
  db.seq += 1;
  return db.seq;
}

// Mirror of errors.py: throws an Error carrying .status, like the real api().
function fail(message, status = 400) {
  const err = new Error(message);
  err.status = status;
  throw err;
}
function requireStr(value, field, maxLen = MAX_NAME_LEN) {
  const text = typeof value === 'string' ? value.trim() : '';
  if (!text) fail(`Please enter a ${field}.`);
  if (text.length > maxLen) fail(`That ${field} is too long (max ${maxLen} characters).`);
  return text;
}
function userFromToken(db, token) {
  const id = token && token.startsWith('mock.') ? Number(token.slice(5)) : NaN;
  const user = db.users.find((u) => u.id === id);
  if (!user) fail('Authentication required.', 401);
  return user;
}

// Serialisers — match the Flask route shapes.
const userPublic = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  yearLevel: u.yearLevel,
  onboarding_done: u.onboarding_done,
});
const subjectPublic = (s) => ({ id: s.id, name: s.name, emoji: s.emoji, colour: s.colour });
const topicPublic = (t) => ({
  id: t.id,
  subjectId: t.subjectId,
  name: t.name,
  emoji: t.emoji,
  standardNumber: t.standardNumber,
  reviewCount: t.reviewCount,
  nextDue: t.nextDue,
});

// Route table keyed by "METHOD path". Each handler gets (db, body, token).
const routes = {
  'POST /api/auth/signup': (db, body) => {
    const name = requireStr(body.name, 'name');
    const email = requireStr(body.email, 'email');
    const password = body.password || '';
    if (password.length < MIN_PASSWORD_LEN)
      fail(`Password must be at least ${MIN_PASSWORD_LEN} characters.`);
    if (db.users.some((u) => u.email.toLowerCase() === email.toLowerCase()))
      fail('An account with that email already exists.');
    const yearLevel = Number(body.yearLevel) || 12;
    const user = { id: nextId(db), name, email, password, yearLevel, onboarding_done: 0 };
    db.users.push(user);
    save(db);
    return { token: `mock.${user.id}`, user: userPublic(user) };
  },

  'POST /api/auth/login': (db, body) => {
    const email = (body.email || '').trim();
    const password = body.password || '';
    if (!email || !password) fail('Please enter your email and password.');
    const user = db.users.find((u) => u.email.toLowerCase() === email.toLowerCase());
    if (!user || user.password !== password) fail('Incorrect email or password.', 401);
    return { token: `mock.${user.id}`, user: userPublic(user) };
  },

  'GET /api/auth/me': (db, _body, token) => ({ user: userPublic(userFromToken(db, token)) }),

  'POST /api/auth/logout': () => ({ ok: true }),

  'PUT /api/user/onboarding': (db, _body, token) => {
    const user = userFromToken(db, token);
    user.onboarding_done = 1;
    save(db);
    return { ok: true };
  },

  'POST /api/subjects': (db, body, token) => {
    const user = userFromToken(db, token);
    const name = requireStr(body.name, 'subject name');
    if (db.subjects.some((s) => s.userId === user.id && s.name === name && !s.archived))
      fail(`You already have a subject called “${name}”.`);
    const subject = {
      id: nextId(db),
      userId: user.id,
      name,
      emoji: (body.emoji || '').trim() || null,
      colour: (body.colour || '').trim() || null,
      archived: 0,
    };
    db.subjects.push(subject);
    save(db);
    return { subject: subjectPublic(subject) };
  },

  'GET /api/subjects': (db, _body, token) => {
    const user = userFromToken(db, token);
    const subjects = db.subjects
      .filter((s) => s.userId === user.id && !s.archived)
      .map((s) => ({
        ...subjectPublic(s),
        topics: db.topics
          .filter((t) => t.subjectId === s.id && !t.archived)
          .map(topicPublic),
      }));
    return { subjects };
  },

  'POST /api/topics': (db, body, token) => {
    const user = userFromToken(db, token);
    const name = requireStr(body.name, 'topic name');
    const subject = db.subjects.find(
      (s) => s.id === body.subjectId && s.userId === user.id && !s.archived,
    );
    if (!subject) fail('That subject could not be found.', 404);
    const topic = {
      id: nextId(db),
      subjectId: subject.id,
      name,
      emoji: (body.emoji || '').trim() || null,
      standardNumber: (body.standardNumber || '').trim() || null,
      reviewCount: 0,
      nextDue: null,
      archived: 0,
    };
    db.topics.push(topic);
    save(db);
    return { topic: topicPublic(topic) };
  },
};

// Same signature the real api() uses internally; token is passed in so this
// module stays decoupled from api.js (no circular import).
async function mockApi(method, path, body, token) {
  await new Promise((r) => setTimeout(r, LATENCY_MS));
  const handler = routes[`${method} ${path}`];
  if (!handler) fail('Not found.', 404);
  return handler(load(), body || {}, token);
}

/* ── js/api.js ── */
// Server communication — token storage + a thin fetch() wrapper.


const getToken = () => localStorage.getItem(TOKEN_KEY);
const setToken = (t) => localStorage.setItem(TOKEN_KEY, t);
const clearToken = () => localStorage.removeItem(TOKEN_KEY);

const REQUEST_TIMEOUT_MS = 10000;

// Call the API. Adds the Bearer token, sends/receives JSON, times out if the
// server is unreachable/slow, and throws an Error (with .status) carrying the
// server's friendly message on failure.
//
// In front-end-only mode (config USE_MOCK) it routes to an in-browser mock with
// the same contract instead of fetching — the rest of the app is unchanged.
async function api(method, path, body) {
  if (USE_MOCK) {
    /* mockApi is bundled in scope */
    return mockApi(method, path, body, getToken());
  }

  const opts = { method, headers: {} };
  const tok = getToken();
  if (tok) opts.headers['Authorization'] = 'Bearer ' + tok;
  if (body !== undefined) {
    opts.headers['Content-Type'] = 'application/json';
    opts.body = JSON.stringify(body);
  }

  // Abort the request if it stalls, so the UI never hangs on a dead server.
  const ac = new AbortController();
  opts.signal = ac.signal;
  const timer = setTimeout(() => ac.abort(), REQUEST_TIMEOUT_MS);

  let res;
  try {
    res = await fetch(API_BASE + path, opts);
  } catch (e) {
    const msg =
      e.name === 'AbortError'
        ? 'The server took too long to respond. Please try again.'
        : "Couldn't reach the server. Check your connection and try again.";
    const err = new Error(msg);
    err.status = 0; // network/timeout, not an HTTP status
    throw err;
  } finally {
    clearTimeout(timer);
  }

  let data = null;
  try {
    data = await res.json();
  } catch {
    /* an empty body is fine */
  }

  if (!res.ok) {
    const err = new Error((data && data.error) || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  return data;
}

/* ── js/screens/dashboard.js ── */
// Dashboard — F1 placeholder. Confirms the full auth → onboarding → data
// round-trip by reading back the subjects/topics the user just created.
// The real priorities + coverage engine lands in slice 2.


async function renderDashboard() {
  const root = $('#screen-dashboard');
  const name = esc(state.currentUser?.name || 'there');

  const { subjects } = await api('GET', '/api/subjects');
  const topicCount = subjects.reduce((n, s) => n + s.topics.length, 0);

  root.innerHTML = `
    <div class="dashboard">
      <h1 class="dashboard-greeting">Kia ora, ${name} 👋</h1>
      <p class="dashboard-sub">${summary(subjects.length, topicCount)}</p>
      ${subjects.length ? subjects.map(subjectCard).join('') : emptyState()}
      <p class="wellbeing-footer">
        Need someone to talk to? Youthline — 0800 376 633 or text 234.
      </p>
    </div>
  `;
}

function summary(subjectCount, topicCount) {
  if (!subjectCount) return "Let's add your first subject to get started.";
  const s = subjectCount === 1 ? 'subject' : 'subjects';
  const t = topicCount === 1 ? 'topic' : 'topics';
  return `You're set up with ${subjectCount} ${s} and ${topicCount} ${t}. Daily review priorities arrive soon.`;
}

function subjectCard(subject) {
  const emoji = esc(subject.emoji || '📚');
  const topics = subject.topics.length
    ? `<ul class="subject-topics">${subject.topics.map(topicChip).join('')}</ul>`
    : '<p class="muted small">No topics yet — you can add them later.</p>';
  return `
    <div class="subject-card">
      <h3>${emoji} ${esc(subject.name)}</h3>
      <p class="subject-meta">${subject.topics.length} ${
        subject.topics.length === 1 ? 'topic' : 'topics'
      }</p>
      ${topics}
    </div>
  `;
}

function topicChip(topic) {
  const std = topic.standardNumber ? `<span class="std">${esc(topic.standardNumber)}</span>` : '';
  return `<li>${esc(topic.name)}${std}</li>`;
}

function emptyState() {
  return `
    <div class="empty-state">
      <p>No subjects yet — but that's okay. You can add them any time.</p>
    </div>
  `;
}

/* ── js/screens/auth.js ── */
// Auth screen — login / signup forms.


/* dedup: MIN_PASSWORD_LEN (already declared above) */

function hydrateAuth() {
  setAuthMode('login');
  ['login-email', 'login-pw', 'signup-name', 'signup-email', 'signup-pw', 'signup-pw2'].forEach(
    (id) => {
      const el = document.getElementById(id);
      if (el) el.value = '';
    },
  );
  hide($('#login-err'));
  hide($('#signup-err'));
}

function setAuthMode(mode) {
  state.authMode = mode;
  $$('.auth-tabs button').forEach((btn) => {
    btn.classList.toggle('active', btn.dataset.mode === mode);
  });
  $('#auth-login').classList.toggle('hidden', mode !== 'login');
  $('#auth-signup').classList.toggle('hidden', mode !== 'signup');
}

async function doLogin(btn) {
  const err = $('#login-err');
  hide(err);
  const email = $('#login-email').value.trim();
  const password = $('#login-pw').value;
  if (!email || !password) {
    err.textContent = 'Please enter email and password.';
    show(err);
    return;
  }
  try {
    const r = await withPending(btn, 'Signing in…', () =>
      api('POST', '/api/auth/login', { email, password }),
    );
    setToken(r.token);
    state.currentUser = r.user;
    navigate('#dashboard');
  } catch (e) {
    err.textContent = e.message || 'Login failed.';
    show(err);
  }
}

async function doSignup(btn) {
  const err = $('#signup-err');
  hide(err);
  const name = $('#signup-name').value.trim();
  const email = $('#signup-email').value.trim();
  const password = $('#signup-pw').value;
  const password2 = $('#signup-pw2').value;
  const yearLevel = $('#signup-year').value;

  if (!name || !email || !password) {
    err.textContent = 'Please fill in all required fields.';
    show(err);
    return;
  }
  if (password !== password2) {
    err.textContent = "Passwords don't match.";
    show(err);
    return;
  }
  if (password.length < MIN_PASSWORD_LEN) {
    err.textContent = `Password must be at least ${MIN_PASSWORD_LEN} characters.`;
    show(err);
    return;
  }

  try {
    const r = await withPending(btn, 'Creating account…', () =>
      api('POST', '/api/auth/signup', { name, email, yearLevel, password }),
    );
    setToken(r.token);
    state.currentUser = r.user;
    navigate('#dashboard');
  } catch (e) {
    err.textContent = e.message || 'Signup failed.';
    show(err);
  }
}

/* ── js/screens/onboarding.js ── */
// Onboarding screen — 3-step flow: welcome → add subject → add topics.


const ob = state.onboarding;

function hydrateOnboarding() {
  resetOnboarding();
  obRender();
}

function obRender() {
  // Progress dots.
  $$('#ob-dots .dot').forEach((d, i) => {
    d.classList.toggle('done', i + 1 < ob.step);
    d.classList.toggle('active', i + 1 === ob.step);
  });
  // Show only the current step.
  [1, 2, 3].forEach((n) => {
    document.getElementById('ob-step-' + n).classList.toggle('hidden', n !== ob.step);
  });
  // Wire the "Other" custom-subject toggle.
  const sel = $('#ob-subj-select');
  if (sel) {
    sel.onchange = () => {
      $('#ob-custom-field').classList.toggle('hidden', sel.value !== '__custom__');
    };
  }
  // Step 3: subject heading + chips.
  if (ob.step === 3) {
    $('#ob-subject-name').textContent = ob.createdSubject ? ob.createdSubject.name : 'your subject';
    renderObChips();
  }
}

function obNext() {
  ob.step = 2;
  obRender();
}

function renderObChips() {
  const wrap = $('#ob-topic-chips');
  if (!ob.addedTopics.length) {
    wrap.innerHTML =
      '<span class="muted small">No topics added yet — you can add them later too.</span>';
    return;
  }
  wrap.innerHTML = ob.addedTopics
    .map(
      (name, i) =>
        `<span class="topic-chip">${esc(name)}
           <span class="chip-remove" data-ob-remove="${i}">✕</span>
         </span>`,
    )
    .join('');
  $$('#ob-topic-chips .chip-remove').forEach((x) => {
    x.onclick = () => {
      ob.addedTopics.splice(+x.dataset.obRemove, 1);
      renderObChips();
    };
  });
}

async function obAddSubject(btn) {
  const sel = $('#ob-subj-select');
  if (!sel.value) {
    toast('Pick a subject first');
    return;
  }
  let name, emoji, colour;
  if (sel.value === '__custom__') {
    name = $('#ob-custom').value.trim();
    if (!name) {
      toast('Type a subject name');
      return;
    }
    emoji = '📘';
    colour = undefined;
  } else {
    const opt = sel.selectedOptions[0];
    name = sel.value;
    emoji = opt.dataset.emoji;
    colour = opt.dataset.colour;
  }
  try {
    const r = await withPending(btn, 'Adding…', () =>
      api('POST', '/api/subjects', { name, emoji, colour }),
    );
    ob.createdSubject = r.subject;
    ob.step = 3;
    obRender();
  } catch (e) {
    toast(e.message);
  }
}

function obAddTopic() {
  const input = $('#ob-topic-input');
  const name = input.value.trim();
  if (!name) return;
  ob.addedTopics.push(name);
  input.value = '';
  renderObChips();
  input.focus();
}

async function obFinish(btn) {
  try {
    await withPending(btn, 'Saving…', async () => {
      if (ob.createdSubject) {
        for (const name of ob.addedTopics) {
          await api('POST', '/api/topics', {
            subjectId: ob.createdSubject.id,
            name,
            emoji: DEFAULT_TOPIC_EMOJI,
          });
        }
      }
      await finishOnboarding();
    });
  } catch (e) {
    toast(e.message);
  }
}

async function obSkip() {
  await finishOnboarding();
}

async function finishOnboarding() {
  await api('PUT', '/api/user/onboarding');
  state.currentUser.onboarding_done = 1;
  resetOnboarding();
  navigate('#dashboard');
}

/* ── js/router.js ── */
// Hash router — decides which screen is visible based on auth + onboarding
// state and the current hash. Runs once on load and again on every hashchange.


const SCREENS = [
  'screen-auth',
  'screen-onboarding',
  'screen-dashboard',
  'screen-subject',
  'screen-settings',
];

function showScreen(id) {
  SCREENS.forEach((s) => {
    const el = document.getElementById(s);
    if (el) el.classList.toggle('hidden', s !== id);
  });
}

function navigate(hash) {
  if (location.hash === hash) route();
  else location.hash = hash;
}

async function route() {
  // No token → not logged in → show auth.
  if (!getToken()) {
    state.currentUser = null;
    hide($('#topbar'));
    showScreen('screen-auth');
    hydrateAuth();
    return;
  }

  // Have a token but no user object yet → fetch it (token may be expired).
  if (!state.currentUser) {
    try {
      state.currentUser = (await api('GET', '/api/auth/me')).user;
    } catch {
      clearToken();
      return route();
    }
  }

  // Logged in but onboarding not finished → onboarding flow.
  if (!state.currentUser.onboarding_done) {
    hide($('#topbar'));
    showScreen('screen-onboarding');
    hydrateOnboarding();
    return;
  }

  // Fully logged in — show topbar and route by hash.
  show($('#topbar'));
  const hash = location.hash || '#dashboard';
  try {
    if (hash === '#settings') {
      showScreen('screen-settings');
    } else if (hash.startsWith('#subject-')) {
      showScreen('screen-subject');
    } else {
      showScreen('screen-dashboard');
      await renderDashboard();
    }
  } catch (e) {
    toast(e.message || 'Something went wrong');
  }
}

/* ── js/main.js ── */
// Composition root — imports every screen handler, wires one delegated click
// listener + keyboard shortcuts, and starts the router. This is the only script
// the HTML loads (`<script type="module" src="js/main.js">`).


// ── Global click delegation ──
// One listener reads data-action from every click and dispatches it. `act` is
// the clicked [data-action] element; handlers that hit the network take it so
// they can show a pending state on that button.
document.body.addEventListener('click', async (e) => {
  // Let an open modal manage its own clicks first.
  if (e.target.closest('#modal-overlay')) {
    if (e.target.closest('[data-action="modal-cancel"]')) closeModal();
    return;
  }

  const act = e.target.closest('[data-action]');
  if (!act) return;

  try {
    switch (act.dataset.action) {
      // Auth
      case 'auth-tab':
        setAuthMode(act.dataset.mode);
        break;
      case 'do-login':
        await doLogin(act);
        break;
      case 'do-signup':
        await doSignup(act);
        break;

      // Onboarding
      case 'ob-next':
        obNext();
        break;
      case 'ob-add-subject':
        await obAddSubject(act);
        break;
      case 'ob-add-topic':
        obAddTopic();
        break;
      case 'ob-finish':
        await obFinish(act);
        break;
      case 'ob-skip':
        await obSkip();
        break;

      // Navigation
      case 'nav-dashboard':
        navigate('#dashboard');
        break;
      case 'nav-settings':
        navigate('#settings');
        break;
      case 'do-logout':
        try {
          await api('POST', '/api/auth/logout');
        } catch {
          /* logging out is best-effort */
        }
        clearToken();
        state.currentUser = null;
        navigate('#');
        route();
        break;
    }
  } catch (err) {
    toast(err.message || 'Something went wrong');
  }
});

// ── Keyboard shortcuts ──
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') {
    if ($('#modal-overlay').classList.contains('show')) closeModal();
    return;
  }
  // Enter submits the auth form.
  if (e.key === 'Enter' && !$('#screen-auth').classList.contains('hidden')) {
    if (state.authMode === 'login') doLogin($('[data-action="do-login"]'));
    else doSignup($('[data-action="do-signup"]'));
  }
  // Enter adds a topic in onboarding step 3.
  if (e.key === 'Enter' && document.activeElement?.id === 'ob-topic-input') {
    obAddTopic();
  }
});

// ── Startup ──
window.addEventListener('hashchange', route);
route(); // modules are deferred, so the DOM is already parsed here.
})();
